apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gsping-demo
  namespace: demo
spec:
  chart:
    spec:
      chart: base
      sourceRef:
        kind: HelmRepository
        name: 99group
      version: 0.1.0
  interval: 1m0s
  releaseName: gsping-demo
  valuesFrom:
    - kind: ConfigMap
      name: values-demo