apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
bases:
  - ../../base/
resources:
  - helm-release.yaml
  - image-scanner.yaml
  - namespace.yaml
configMapGenerator:
  - name: values-demo
    files:
      - values.yaml=values-demo.yaml
generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
  annotations:
    note: generated