apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: base
  namespace: demo
spec:
  url: urbanindo.github.io/99-charts
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: base
  namespace: demo
spec:
  interval: 5m
  chart:
    spec:
      chart: base
      version: '0.1.0'
      sourceRef:
        kind: HelmRepository
        name: base
        namespace: demo
      interval: 1m
  values:
    replicaCount: 1