apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - image-scanner.yaml
  - namespace.yaml
generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
  annotations:
    note: generated